### ISSUE TITLE
Windows Form KeyAuth Download

### ISSUE THREAD

**Issue by MRXCLAYZERO** [KeyAuth/KeyAuth-CSHARP-Example#25]
Hello, this Windows form works well except for one thing. This window appears

![unknown](https://user-images.githubusercontent.com/76757293/183301319-9c898b70-76ed-4bbf-88e3-968027f5745a.png)

, I don't want that at all. I just want it to download a file as soon as you register or log in. I also filled in the KeyAuthApp.download Id.

![unknown](https://user-images.githubusercontent.com/76757293/183301213-1f7d7d93-678a-4b2c-940a-12826124bfe5.png)

**Comment by MRXCLAYZERO** [comment]
But i dont want the message box, i just want to download a file as soon ypu register or login. I dont want the main.cs. If i try to delete that and make another main.cs (my own) there is popping a lot of errors like Lincense thing and so on

**Comment by mazk5145** [comment]
![image](https://user-images.githubusercontent.com/79049205/183442109-af42e17b-75e7-416a-abc2-5a11c362dafb.png)
No chat system.

**Comment by mazk5145** [comment]
is causing that

**Comment by wnelson03** [comment]
Fixed, thank you mazk for your help.
