### ISSUE TITLE
Exception Thrown

### ISSUE THREAD

**Issue by eccentricPACHARA** [KeyAuth/KeyAuth-CSHARP-Example#26]
Exception Thrown System.NullReferenceException: 'Object reference not set to an instance of an object.'

![image](https://user-images.githubusercontent.com/47096657/186567779-9c512382-de18-43cc-8a72-a13385c39569.png)

**Comment by eccentricPACHARA** [comment]
line 92 @ Main.Designer.cs

**Comment by eccentricPACHARA** [comment]
and when I build it and click login or register I got unhandled exception
![image](https://user-images.githubusercontent.com/47096657/186568743-97792db8-8177-497b-a7a5-6b1d494b5402.png)
![image](https://user-images.githubusercontent.com/47096657/186568772-179a7eb0-11ce-44e3-b69f-afa9dc7e59a2.png)

**Comment by wnelson03** [comment]
Fixed, thanks for making us aware.
