### ISSUE TITLE
Ban function not working

### ISSUE THREAD

**Issue by Grim1321** [KeyAuth/KeyAuth-CSHARP-Example#29]
ban function not working,is it a bug?

**Comment by wnelson03** [comment]
Works well on my end.
![image](https://user-images.githubusercontent.com/83034852/198858700-21c6d4aa-b49e-4cfd-9368-e4fc34565458.png)
![image](https://user-images.githubusercontent.com/83034852/198858702-8b43e4e9-e6fa-4cf4-9363-8419e3389cef.png)
Do note, you can only execute the ban command after the user is logged in.
