### ISSUE TITLE
still shows online user after delete all users

### ISSUE THREAD

**Issue by imrroot** [KeyAuth/KeyAuth-CSHARP-Example#30]
hi i tried to get online users in my app but after deleted all users in my panel
it still show users i deleted as online i dont  know whats is problem 

im using fetchOnline function to get users

**Comment by wnelson03** [comment]
Online users are cached in Redis for 30 minutes.

Currently, I don't purge the cache of the online users on events like Delete All Users or Killing Sessions, however I may consider adding this.

Were you hoping to see the online users be deleted when you deleted all users? Or were you just curious why they weren't? If you waited 30 minutes and tried again, the online users would've been empty at that point.

**Comment by imrroot** [comment]
> Online users are cached in Redis for 30 minutes.
> 
> Currently, I don't purge the cache of the online users on events like Delete All Users or Killing Sessions, however I may consider adding this.
> 
> Were you hoping to see the online users be deleted when you deleted all users? Or were you just curious why they weren't? If you waited 30 minutes and tried again, the online users would've been empty at that point.


hmm ok thanks for your help but i think 30 minutes its long time for refresh user list 
so as you said please add option to delete cache too :D
thanks for your help
